# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ticket_pb2 as ticket__pb2


class RestauranteUniversitarioStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComprarTicket = channel.unary_unary(
                '/RestauranteUniversitario/ComprarTicket',
                request_serializer=ticket__pb2.CompraRequisicao.SerializeToString,
                response_deserializer=ticket__pb2.CompraResposta.FromString,
                )


class RestauranteUniversitarioServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ComprarTicket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RestauranteUniversitarioServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComprarTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.ComprarTicket,
                    request_deserializer=ticket__pb2.CompraRequisicao.FromString,
                    response_serializer=ticket__pb2.CompraResposta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RestauranteUniversitario', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RestauranteUniversitario(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ComprarTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RestauranteUniversitario/ComprarTicket',
            ticket__pb2.CompraRequisicao.SerializeToString,
            ticket__pb2.CompraResposta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
