# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ticket.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cticket.proto\"A\n\x10\x43ompraRequisicao\x12\x17\n\x0fmatricula_aluno\x18\x01 \x01(\t\x12\x14\n\x0cvalor_boleto\x18\x02 \x01(\x01\"@\n\x0e\x43ompraResposta\x12\x18\n\x10\x63odigo_de_barras\x18\x01 \x01(\t\x12\x14\n\x0cvalor_boleto\x18\x02 \x01(\x01\x32Q\n\x18RestauranteUniversitario\x12\x35\n\rComprarTicket\x12\x11.CompraRequisicao\x1a\x0f.CompraResposta\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ticket_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMPRAREQUISICAO._serialized_start=16
  _COMPRAREQUISICAO._serialized_end=81
  _COMPRARESPOSTA._serialized_start=83
  _COMPRARESPOSTA._serialized_end=147
  _RESTAURANTEUNIVERSITARIO._serialized_start=149
  _RESTAURANTEUNIVERSITARIO._serialized_end=230
# @@protoc_insertion_point(module_scope)
